# Generated by Django 5.1.3 on 2025-04-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('PayPal', 'PayPal')], default='Credit Card', max_length=50),
        ),
    ]
