# Generated by Django 5.2 on 2025-05-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cinemahall_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.FloatField(default=125.0),
        ),
    ]
