# Generated by Django 5.2 on 2025-05-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_showtime_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ManyToManyField(related_name='reservations', to='main.seat'),
        ),
    ]
