# Generated by Django 5.2 on 2025-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reservation_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='show_time',
            field=models.ManyToManyField(related_name='show_times', to='main.showtime'),
        ),
    ]
