# Generated by Django 5.2 on 2025-05-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_seat_show_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='show_time',
        ),
        migrations.AddField(
            model_name='showtime',
            name='seat',
            field=models.ManyToManyField(related_name='show_times', to='main.seat'),
        ),
    ]
