# Generated by Django 5.2 on 2025-05-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_seat_show_time_showtime_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='is_available',
        ),
    ]
