# Generated by Django 5.2.1 on 2025-06-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_purchasehistory_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_confirmed',
        ),
    ]
